### ISSUE TITLE
Tek Boynuz Çok Cihaz

### ISSUE THREAD

**Issue by ToygarVarli** [barisdinc/Aselsan_Boynuz#2]
Boynuz ile birden fazla telsizin yönetimi sağlanabilir mi ? 

VHF ve UHF olarak 2 adet cihazımı tek bir kontrol ünitesi ile kontrol edebilsem ,

Tek mayk girişi tek ekran tek tuş takımı 2 cihaz olsa.

**Comment by barisdinc** [comment]
teorik olarak mumkun.. MCU tarafi I2C BUS uzerinden bilgileri ekrana yazarken bir taraftan da tus takimi bilgilerini ayni bus uzerinden geri okuyor..
I2C elemanlarinin adresleri ayni oldugu icin tek bus uzerinden degil, ama 2 ader I2C baglantisi olan bir islemci kullanilirsa boynuz icerisinde (ya da en azindan biri software I2C olabilir), telsiz MCU lari ile haberlesirse, giden gelen bilgiler tek bir displayde gosterilip, secilen telsiz icin tus takimi bilgileri geri gonderilebilir.
Iki cihaz ustuste durumu icin de birsey yapmak gerekecek fiziksel olarak BOYNUZ tasarimina..

SORU: bunu yapmaya deger mi ?

**Comment by ToygarVarli** [comment]
Haklısınız Barış Hocam ,

Attığımız taş ürküttüğümüz kuşa değmeyebilir.
