### ISSUE TITLE
I2C Protokol Çözümlemesi

### ISSUE THREAD

**Issue by ToygarVarli** [barisdinc/Aselsan_Boynuz#3]
Herkese merhaba ,

Orjinal aselsan donanıma sahip bir cihaz ile boynuz için Arduino nano ile çalışmaya başladım.  İlk aşamada 2.4 inchlik bir touch lcd ile aselsan MCU'dan gelen verileri ekrana yazdırmaya çalışıyorum.

Arduino 'yu LCD Slave adresi olan (0x38)'e slave olarak I2C hattına dahil ettim ve Aselsan MCU'dan gelen datayı arduino ile dinleyip seri porttan pc ekranına yazmaya başladım.

Ekrana KN 01 yazmak için MCU'nun gönderdiği değerler ,

`228 192 0 32 3 104 14 22 0 0 5 38 38 0  96 0  0 0 0 0 0 0 `

şeklinde.

Tamsat kitinin LCD'ye gönderdiği değerler ise

`5 3 128 128 225 96 0 0 0 18 96 96 0 98 0`

 Fakat bu datayı nasıl decode edeceğim konusunda yardıma ihtiyacım var.

Tamsat kitinden gelen datayı binary olarak çevirdiğim zaman fonts dosyasındaki uygun byte'ları bulabiliyorum (örn , K harfi B00000101, B00000011, B0000000 'Den oluşuyor   bu da => 5 = 101 , 3 => 11  şeklidne decode edebiliyorum.)

**Comment by barisdinc** [comment]
Bunun icin semaya birazcik bakabilirsin...
https://github.com/barisdinc/ASELSAN_4822/blob/master/docs/4822-0002_MV4822-MV4826_AT_Bakim_Onarim_A3.pdf
dokumaninin K1 Gosterge kartina bakarsan I2C hattinin hem LCD surucusune hem de TUS takimini okuyan devreye bagli oldugunu gorursun (keza tus takiminin bir kismi LED lere ve aydinlatmaya da bagli ve I2C uzerinden suruluyor)

https://github.com/barisdinc/ASELSAN_4822/blob/master/docs/4822-0002_MV4822-MV4826_AT_Bakim_Onarim_RevA.pdf
dokumaninda sayfa 175 daha detayli aslinda...

tus takimi icin PCF8574 den 2 tane var... birine satir bilgisini yaziyor, sonra da surunlardan hangilerine karsilik geldigini okuyor.. cakisan yerlerdeki tuslara basilmis oldugunu anliyoruz...

adres kismina bakacak olursan da A0 A1 pinlerinin birinde topraga cekildigini gorursun.. detaylar icin PCF8574 datasheet ine bakabilirsin (https://github.com/barisdinc/Aselsan_Boynuz/blob/master/Docs/pcf8574.pdf    ADRES 0100-A2-A1-A0  yani adresi 20 21 22 ve 23 olabiliyor... semaya bakinca da sekil 6-1 sayfa 6-3 (179) birinde A2-A1-A0 in 000 digerinde 001 oldugunu gorursunyani birinin adresi 20 digeri 21)

LCD icin ise dokuman https://github.com/barisdinc/Aselsan_Boynuz/blob/master/Docs/PCF8576.pdf
bunun adresi de 0111000 ve yine A0 A1 A2 ama hepsi toprakta.. yani adresimiz 70h)

bu bilgilerre ASELSAN kodumuzdaki 60. satir civarinda asagidaki gibi e ulasabilirsin

#define PCF8576_LCD         0x38 //B111000   // This is the address of the PCF on the i2c bus
#define PCF8574_KEYB        0x20 //PCF854 connected to LED and KEYBOARD
#define PCF8574_KEYB_LED    0x21 //PCF8574 connected to KEYBOARD and has interrupt connected to MCU

sumdi bu ne demek...
krana ne yazildigini takip edecek isek 0x38 adresine slave olmaliyiz, tus takimini dinleyecek ya da isiklari yakacak isek de 20 ve 21'e... mantiklarini ve ilseyisini bilahare baska bir issue kapsmainda tartisidriz..

Gelelim LCD yi anlama konusuna. .bunun icin 8576 nin PDF ini iyi hatim etmek lazim.. Font memory si, registerlari ne demek diye... Neticede orjinal aselsan kodu baska registerleri kullanarak islemis olailir.. ben direk PDF den isime yarayanlari kullandim.. BOYNUZ icin sanki en kolay kullanim su sekilde olabilir (temel mantik aslinda I2C den paralel olarak pinlere segmentler halinde veri basmak):

Sekil 6-1 e ek olarak sayfa E-9 (330 ve 331) e bakmani oneririm... burada hangi bacaklara hengi ekran pinlerinin bagli oldugunu builursun..

Ben bu pinlere karsilik gelen yapida kendimce bir FONT yapisi uydurdum, ama sanirim orjinal aselsan baska birseyler yapmis ama onemli degil neticede dogru registerleri dinlersek ya da ekranda hangi yerleri yakacagimizi bilirsek ilerleyebiliris.

kolay olmasi acisindan sivi kristal gostergedeki gibi 18 parcali harflerden ve bunlarin sira ile yakilmasindan ilerlemeliyiz...
LCD surucu komutlari datasheet inin 23. sayfasindan itibaren basliyor

**Comment by ToygarVarli** [comment]
Merhaba Barış Hocam , 

Evet söylediğiniz gibi arduino'yu i2c hattına slave gibi dahil edip MCU'dan LCD'ye gelen veriyi arduino'da karşılayıp sonrasında da LCD'ye yazdırmaya çalışıyorum.

Döküman referanslarını okumaya başladım ilerleme katedebilirsem mutlaka bilgi veriyor olacağım.

Teşekkürler.

**Comment by ToygarVarli** [comment]
Hocam selamlar ,

Bir süredir çalışmaya devam ediyorum , uzun ve sıkıcı bir yazı yazıp bayram tatilinden dolayı olmayan pazartesi sendromunu yazımla hortlatmak isterim :)

Bizim tamsatta kullandığımız K harfi ,

Görüntüdeki K harflerinden soldaki. Aselsan MCU'nun gönderdiği sağdaki.  Aselsan 1 segment daha fazla yakıyor kısacası.
Zaten önceki mesajınızda da font dosyasını ihtiyacımızı görecek şekilde oluşturduğumuzu **bundan dolayı farklılıklar olabileceğini konuşmuştuk**. 

Fakat boynuz'un hem tamsat hem de orjinal aselsan cihazlarla çalışabilmesi için fontların aynı olması gerekiyor diye düşünüyorum. 

Bu yüzden tamsat içindeki K harfini aselsan'daki K harfi ile aynı yaptım.  Böylece orjinal aselsan'ın I2C'den gönderdiği değerleri tamsat'ın oluşturduğu değerler ile karşılaştırırken işimi kolaylaştırıyor.



```
 B00100000, B00000011, B01101000, //K - Tamsat
 B00100000, B00000011, B01100000, //K - Aselsan
```
şeklinde güncelledim.

Aselsan'ın K harfi için oluşturduğu binary değelerin HEX karşılıklarına bakalım ,

`0x20 , 0x03 , 0x60`

Fakat aselsan ekrana KN yazmak için 

`0x20 , 0x03, 0x68 , 0x0E , 0x16, 0x00`

değerlerini gönderiyor.  

Yani K harfi için font mappinginde son değer 0x60 olmasına rağmen aselsan 0x68 gönderiyor. 

Arduino ile LCD'ye 0x20,0x3,0x68 gönderdiğim zaman ise sonraki karakterin bir parçasının da aydınlandığını görüyorum. (testimiz özelinde n harfinin g segmenti)

![image](https://user-images.githubusercontent.com/3975634/89182280-1e697c00-d59e-11ea-8f9e-a4ca18496c96.png)


Bizim tamsatta kullandığımız lcd font oluşturma kısmında 

`    if (idx > 0) {                       //third BYTE should include previous character if this is not the first
      matrix[3 * idx + 2] = font[(pos * 3) + 2] | (matrix[3 * (idx + 1)] & B00001111) | Position_Signs[idx][2]; // four bits should be from the existing character
    }`

şöyle bir işlemimiz var. 

3.Byte bir **önceki** karakterden 4 bit içerir şeklinde. Fakat aselsan sanki 3.byte bir **sonraki** karakterden 4bit içerir gibi bir logic ile ilerlemiş. Tabii eğer bu tespitim doğru ise bizim tamsatta kullandığımız 1 karakter için 3 byte array oluştur bunu LCD'ye yolla , sonra sonraki karaktere geç logic'inin değişmesi gerekiyor gibi çünkü her 20.bit'ten sonra bir sonraki karakterin bitleri gelmeye başlıyor. 


Tüm tespit ettiğim / ettiğimi sandığım konuları toplayacak olursam şöyle bir teorim var.

Her karakterin 20bit gerektirdiğini biliyoruz zaten. 

Ama biz 3 bytelık arrayler oluşturduğumuz için 24bit oluyor aslında.

Ekrana TAMSAT yazmak istediğimizi düşünürsek ,

Elimizde 6x3 byte = 18 byte oluyor. 

İlk 3 byte'ın 20 biti T harfi için. Kalan 4 bit de A harfinin ilk bytenın 4 bitini içermeli.

Bu durumda 18 bytelık arrayi 3er 3er göndermek yerine önce 18 byte'ı oluşturmalı ,

Sonra da bitwise işlemleri ile her 20bitte bir sonraki byte'ın 4 bitini bir önceki byte'ın son 4 bitine yazmalıyız. ve LCD'ye gönderirken 18 byte'ı tek seferde yollamalıyız. (Burada bahsettiğim bitwise işlemi nasıl yapabileceğim konusunda pek fikrim yok açıkcası)

gibi değişik bir sonuca ulaşıyorum.

Şimdilik tespit edebildiğim kısımlar bunlar. Bunları paylaşıp değerli yorumlarınızı  almak isterim.


![image](https://user-images.githubusercontent.com/3975634/89181348-32ac7980-d59c-11ea-9f17-a440b08a1df2.png)
