### ISSUE TITLE
Donanım ile İlgili Kararlar

### ISSUE THREAD

**Issue by ToygarVarli** [barisdinc/Aselsan_Boynuz#5]
Barış Hocam Selamlar ,

Elimde bulunan 2.4 inch TFT touch  LCD ile Aselsandan gelen bilgileri görüntüleyebiliyorum artık :)

Fakat elimdeki arduino uno'nun neredeyse tüm pinlerini işgal ediyor.

LCD olarak nasıl bir şey kullanacağız ? Bununla ilgili bir karar var mı acaba ? (Büyüklüğü , haberleşme türü v.s)

Nextion HMI'lar var. Fiyatları biraz yüksek ama , basit bir program ile kullanıcı kendi arayüzlerini tasarlayabiliyor.

Ayrıca boynuz'daki mcu olarak atmega328 mi kullanacağız ? 

-Ayrıca aydınlatma ve tuş takımı için 2 adet daha i2c slave olmalı. Bu durumda arduino'yu totalde 3 farklı slave olarak tanıtmamız gerekecek.

2.4 lcd ile çalışmamdan bir kare.

![WhatsApp Image 2020-08-03 at 23 58 08](https://user-images.githubusercontent.com/3975634/89227372-3b29a200-d5e6-11ea-906f-a2a9ba337672.jpeg)

**Comment by barisdinc** [comment]
Merhabalar, aslinda boynuz icinde buluncak islemci icin ARDUINO (atmel) ya da benzeri bir kisitimiz yok.. dogrusunu istersen zamaninda hurdanan aldigim birkacbin tane MSP430 lari degerlendirmeyi de dusunuyorum bu proje icin bir yandan...
o yuzden ekran icin de cok bir kisitimiz yok.

aydinlatma ve tus takimi konusund haklisin...

**Comment by ToygarVarli** [comment]
Hocam peki ekran olarak grafik lcd kullanabilir miyiz?

Elimde 240x128 bir grafik lcd var. Arkasında da i2c backpack mevcut. 2 pin ile olayı çözebiliriz. Siz readme dosyasında renkli lcd olarak madde yazmışsınız o yüzden bende bu tarz lcd ye yönelmiştim. Grafik lcd kullanabilirsek harika olur. 

Msp430 konusunda ise elimde, 

exp430fr4133 geliştirme kiti ve

MSP430G2xxx launch pad mevcut. 

Bu mcular ile çalışabilir miyiz? Texas tarafına çok hakim olmadığım için mcu bazlı değişiklikler oluyor mu emin değilim.

Yönlendirebileceğiniz spesifik bir mcu var ise onu edinmeye çalışıp oradan da devam edebilirim.

**Comment by barisdinc** [comment]
dedigim gibi , bir kisitlamamiz yok.. Amacimiz en uygun butce ile en verimli cihazi yapmak.
elimde msp430fe4272ipmr, msp430fe425aipmr  ve msp430f436ipzr var.

haliyle herhangi bir MSP430 ile calisma yapabiliriz, daha sonra diger islemciye port etmek kolay olur.. sanirim cok detay donanimsal kodlama (timer secimi, vb.) yapmayiz.

sadece derleyici olarak GCC ya da open birsey kullanmayi tercih ederim, herkes ulasabilir olsun diye

**Comment by ToygarVarli** [comment]
Tamamdır hocam ,

O halde elimdeki kaynaklar projede çalışmak için yeterli. (MSP430 ve Grafik LCD)

MSP430'ları programlarken Energia IDE kullanıyordum hocam ben. 

Bildiğim kadarı ile GCC ile derliyor ve arduino gibi library desteği vs açısından da oldukça zengin. Sakıncası yok ise buradan devam edeyim ?

**Comment by barisdinc** [comment]
Evet GCC kullaniyormus... onunla devam edebilrisin..

kolay gele

**Comment by ToygarVarli** [comment]
Teşekkür ederim hocam.
